<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Configurations>Debug;Release;V2XController-Debug</Configurations>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<ApplicationIcon>V2x icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="V2x icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.5" />
    <PackageReference Include="System.IO.Ports" Version="10.0.2" />
    <PackageReference Include="System.Management" Version="10.0.10" />
    <PackageReference Include="Uno.UI" Version="5.6.99" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ComCommon">
      <HintPath>..\..\..\..\Downloads\ModbusLib\ComCommon.dll</HintPath>
    </Reference>
    <Reference Include="Common">
      <HintPath>..\..\..\..\Downloads\ModbusLib\Common.dll</HintPath>
    </Reference>
    <Reference Include="Logger">
      <HintPath>..\..\..\..\Downloads\ModbusLib\Logger.dll</HintPath>
    </Reference>
    <Reference Include="ModbusNewLib">
      <HintPath>..\..\..\..\Downloads\ModbusLib\ModbusNewLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
