<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  	<OutputType>WinExe</OutputType>
  	<TargetFramework>net8.0-windows8.0</TargetFramework>
  	<Nullable>enable</Nullable>
 	 <ImplicitUsings>enable</ImplicitUsings>
  	<UseWPF>true</UseWPF>
  <AssemblyVersion>3.2.0.0</AssemblyVersion>
  <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
  <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
</PropertyGroup>

<Target Name="IncrementBuildNumber"
        BeforeTargets="PrepareForBuild"
        Condition="'$(DesignTimeBuild)' != 'true'
                   AND '$(MSBuildProjectName)' == 'V2XController'">

  <Exec
    Command="powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(ProjectDir)IncrementBuild.ps1&quot;" />

</Target>

  <ItemGroup>
    <Content Include="V2x icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.5" />
    <PackageReference Include="System.IO.Ports" Version="10.0.2" />
    <PackageReference Include="System.Management" Version="10.0.10" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ComCommon">
      <HintPath>..\..\..\..\Downloads\ModbusLib\ComCommon.dll</HintPath>
    </Reference>
    <Reference Include="Common">
      <HintPath>..\..\..\..\Downloads\ModbusLib\Common.dll</HintPath>
    </Reference>
    <Reference Include="Logger">
      <HintPath>..\..\..\..\Downloads\ModbusLib\Logger.dll</HintPath>
    </Reference>
    <Reference Include="ModbusNewLib">
      <HintPath>..\..\..\..\Downloads\ModbusLib\ModbusNewLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="IncrementBuildNumber" BeforeTargets="GenerateAssemblyInfo">

    <Exec
      Command="powershell -ExecutionPolicy Bypass -File &quot;$(ProjectDir)IncrementBuild.ps1&quot;" />

    <ReadLinesFromFile File="$(ProjectDir)build.txt">
      <Output TaskParameter="Lines" PropertyName="BuildNumber" />
    </ReadLinesFromFile>

    <PropertyGroup>
      <FileVersion>$(BuildNumber)</FileVersion>
      <InformationalVersion>$(BuildNumber)</InformationalVersion>
    </PropertyGroup>

    <Message
      Text="V2XController build version: $(BuildNumber)"
      Importance="high" />

  </Target>

</Project>